#################################################
## Qubership custom template. HTTPRoute for oauth2Proxy
#################################################
{{- if .Values.oauth2Proxy.enabled -}}
{{- if .Values.oauth2Proxy.gateway.enabled -}}
{{- $fullname := (include "oauth2-proxy.fullname" .) -}}
{{- $Global := . -}}

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: oauth2Proxy
    component: oauth2Proxy-httproute
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- include "oauth2-proxy.labels" $Global | nindent 4 }}
    {{- if .Values.oauth2Proxy.gateway.labels }}
    {{- tpl (toYaml .Values.oauth2Proxy.gateway.labels) . | nindent 4 }}
    {{- end }}
  {{- with .Values.oauth2Proxy.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.oauth2Proxy.gateway.parentRefs }}
  parentRefs:
    {{- tpl (toYaml .) $Global | nindent 4 }}
  {{- end }}
  {{- with .Values.oauth2Proxy.gateway.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $Global | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.oauth2Proxy.gateway.rules }}
    - matches:
        {{- if .matches }}
        {{- toYaml .matches | nindent 8 }}
        {{- else }}
        - path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value | default "/" }}
        {{- end }}
      {{- if .filters }}
      filters:
        {{- toYaml .filters | nindent 8 }}
      {{- end }}
      backendRefs:
        - group: ''
          kind: Service
          name: {{ $fullname }}
          port: {{ (index .backendRefs 0).port | int }}
          {{- if .weight }}
          weight: {{ .weight }}
          {{- else }}
          weight: 1
          {{- end }}
    {{- end }}

---
#################################################
## Qubership custom template. BackendTLSPolicy
#################################################
{{- if .Values.oauth2Proxy.gateway.backendTLSPolicy.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ $fullname }}-backend-tls-policy
  namespace: {{ .Release.Namespace }}
  labels:
    tier: oauth2Proxy
    component: oauth2Proxy-httproute
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- include "oauth2-proxy.labels" $Global | nindent 4 }}
  {{- with .Values.oauth2Proxy.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: {{ $fullname }}
  validation:
    {{- if .Values.oauth2Proxy.gateway.backendTLSPolicy.hostname }}
    hostname: {{ tpl .Values.oauth2Proxy.gateway.backendTLSPolicy.hostname $Global | quote }}
    {{- end }}
    {{- if .Values.oauth2Proxy.gateway.backendTLSPolicy.subjectAltNames }}
    subjectAltNames:
    {{- toYaml .Values.oauth2Proxy.gateway.backendTLSPolicy.subjectAltNames | nindent 6 }}
    {{- end }}
    {{- if .Values.oauth2Proxy.gateway.backendTLSPolicy.caCertificateRefs }}
    caCertificateRefs:
    {{- toYaml .Values.oauth2Proxy.gateway.backendTLSPolicy.caCertificateRefs | nindent 6 }}
    {{- end }}
    {{- if .Values.oauth2Proxy.gateway.backendTLSPolicy.wellKnownCACertificates }}
    wellKnownCACertificates: {{ tpl .Values.oauth2Proxy.gateway.backendTLSPolicy.wellKnownCACertificates $Global | quote }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}