qubership-spark-customized: ghcr.io/netcracker/qubership-spark-customized:2.2.1
qubership-spark-on-k8s-transfer: ghcr.io/netcracker/qubership-spark-on-k8s-transfer:2.2.1
qubership-spark-on-k8s-tests: ghcr.io/netcracker/qubership-spark-on-k8s-tests:2.2.1
qubership-spark-operator: ghcr.io/netcracker/qubership-spark-operator:2.2.1
qubership-spark-customized-py: ghcr.io/netcracker/qubership-spark-customized-py:2.2.1
qubership-deployment-status-provisioner: ghcr.io/netcracker/qubership-deployment-status-provisioner:0.2.3
oauth2_proxy_release-image: quay.io/oauth2-proxy/oauth2-proxy:v7.13.0

